-- Apply this SQL to create the feed_cost_log table and related structures
-- This will fix the "Could not find the table 'public.feed_cost_log'" error

-- Add cost tracking fields to hogs table
ALTER TABLE hogs 
ADD COLUMN IF NOT EXISTS purchase_price DECIMAL(10,2) DEFAULT 0.00;

ALTER TABLE hogs 
ADD COLUMN IF NOT EXISTS total_feed_cost DECIMAL(10,2) DEFAULT 0.00;

ALTER TABLE hogs 
ADD COLUMN IF NOT EXISTS total_cost DECIMAL(10,2) GENERATED ALWAYS AS (purchase_price + total_feed_cost) STORED;

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_hogs_purchase_price ON hogs(purchase_price);
CREATE INDEX IF NOT EXISTS idx_hogs_total_feed_cost ON hogs(total_feed_cost);
CREATE INDEX IF NOT EXISTS idx_hogs_total_cost ON hogs(total_cost);

-- Create feed_cost_log table to track daily feed consumption costs
CREATE TABLE IF NOT EXISTS feed_cost_log (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  hog_id BIGINT NOT NULL REFERENCES hogs(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  feed_category VARCHAR(20) NOT NULL CHECK (feed_category IN ('starter', 'grower', 'finisher')),
  amount_kg DECIMAL(8,2) NOT NULL CHECK (amount_kg > 0),
  unit_price DECIMAL(8,2) NOT NULL CHECK (unit_price >= 0),
  total_cost DECIMAL(10,2) NOT NULL CHECK (total_cost >= 0),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(hog_id, date, feed_category)
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_feed_cost_log_hog_id ON feed_cost_log(hog_id);
CREATE INDEX IF NOT EXISTS idx_feed_cost_log_date ON feed_cost_log(date);
CREATE INDEX IF NOT EXISTS idx_feed_cost_log_category ON feed_cost_log(feed_category);
CREATE INDEX IF NOT EXISTS idx_feed_cost_log_hog_date ON feed_cost_log(hog_id, date);

-- Add comments for documentation
COMMENT ON TABLE feed_cost_log IS 'Tracks daily feed consumption costs for each hog';
COMMENT ON COLUMN feed_cost_log.hog_id IS 'Reference to the hog';
COMMENT ON COLUMN feed_cost_log.date IS 'Date of feed consumption';
COMMENT ON COLUMN feed_cost_log.feed_category IS 'Type of feed consumed (starter, grower, finisher)';
COMMENT ON COLUMN feed_cost_log.amount_kg IS 'Amount of feed consumed in kilograms';
COMMENT ON COLUMN feed_cost_log.unit_price IS 'Price per kilogram of feed';
COMMENT ON COLUMN feed_cost_log.total_cost IS 'Total cost for this consumption (amount_kg * unit_price)';

-- Enable RLS
ALTER TABLE feed_cost_log ENABLE ROW LEVEL SECURITY;

-- Create RLS policies for feed_cost_log
CREATE POLICY "Users can view their own feed cost logs" ON feed_cost_log
FOR SELECT USING (auth.jwt() ->> 'role' IN ('admin', 'user'));

CREATE POLICY "Admins can insert feed cost logs" ON feed_cost_log
FOR INSERT WITH CHECK (auth.jwt() ->> 'role' = 'admin');

CREATE POLICY "Admins can update feed cost logs" ON feed_cost_log
FOR UPDATE USING (auth.jwt() ->> 'role' = 'admin');

CREATE POLICY "Admins can delete feed cost logs" ON feed_cost_log
FOR DELETE USING (auth.jwt() ->> 'role' = 'admin');

-- Grant permissions
GRANT ALL ON feed_cost_log TO authenticated;
GRANT SELECT ON feed_cost_log TO anon;

-- Create function to update hog feed costs
CREATE OR REPLACE FUNCTION update_hog_feed_cost()
RETURNS TRIGGER AS $$
BEGIN
  -- Update the hog's total feed cost when a new feed cost log is added
  UPDATE hogs 
  SET total_feed_cost = (
    SELECT COALESCE(SUM(total_cost), 0) 
    FROM feed_cost_log 
    WHERE feed_cost_log.hog_id = NEW.hog_id
  )
  WHERE id = NEW.hog_id;
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger to automatically update hog feed costs
DROP TRIGGER IF EXISTS trigger_update_hog_feed_cost ON feed_cost_log;
CREATE TRIGGER trigger_update_hog_feed_cost
AFTER INSERT ON feed_cost_log
FOR EACH ROW
EXECUTE FUNCTION update_hog_feed_cost();

-- Update existing hogs' total_feed_cost based on any existing data
UPDATE hogs 
SET total_feed_cost = COALESCE(
  (SELECT SUM(total_cost) 
   FROM feed_cost_log 
   WHERE feed_cost_log.hog_id = hogs.id), 
  0
);

-- Verify table creation
SELECT 
  table_name, 
  table_type 
FROM information_schema.tables 
WHERE table_schema = 'public' 
AND table_name = 'feed_cost_log';
