-- Add cost tracking fields to hogs table
-- This will track the initial purchase price and calculate total costs

-- Add purchase_price field to track initial cost of each hog
ALTER TABLE hogs 
ADD COLUMN purchase_price DECIMAL(10,2) DEFAULT 0.00;

-- Add total_feed_cost field to track cumulative feed consumption cost
ALTER TABLE hogs 
ADD COLUMN total_feed_cost DECIMAL(10,2) DEFAULT 0.00;

-- Add total_cost field for easy calculation of total investment
ALTER TABLE hogs 
ADD COLUMN total_cost DECIMAL(10,2) GENERATED ALWAYS AS (purchase_price + total_feed_cost) STORED;

-- Create indexes for better performance
CREATE INDEX idx_hogs_purchase_price ON hogs(purchase_price);
CREATE INDEX idx_hogs_total_feed_cost ON hogs(total_feed_cost);
CREATE INDEX idx_hogs_total_cost ON hogs(total_cost);

-- Add comments for documentation
COMMENT ON COLUMN hogs.purchase_price IS 'Initial purchase price of the hog';
COMMENT ON COLUMN hogs.total_feed_cost IS 'Cumulative cost of feed consumed by this hog';
COMMENT ON COLUMN hogs.total_cost IS 'Total investment in this hog (purchase price + feed cost)';

-- Create feed_cost_log table to track daily feed consumption costs
CREATE TABLE IF NOT EXISTS feed_cost_log (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  hog_id BIGINT NOT NULL REFERENCES hogs(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  feed_category TEXT NOT NULL CHECK (feed_category IN ('starter', 'grower', 'finisher')),
  amount_kg DECIMAL(8,3) NOT NULL,
  unit_price DECIMAL(8,2) NOT NULL,
  total_cost DECIMAL(10,2) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes for feed_cost_log
CREATE INDEX idx_feed_cost_log_hog_id ON feed_cost_log(hog_id);
CREATE INDEX idx_feed_cost_log_date ON feed_cost_log(date);

-- Add RLS policies for feed_cost_log
ALTER TABLE feed_cost_log ENABLE ROW LEVEL SECURITY;

-- Only authenticated users can read feed cost logs
CREATE POLICY "Users can view feed cost logs" ON feed_cost_log
FOR SELECT USING (auth.role() = 'authenticated');

-- Only admins can insert feed cost logs
CREATE POLICY "Admins can insert feed cost logs" ON feed_cost_log
FOR INSERT WITH CHECK (auth.jwt() ->> 'role' = 'admin');

-- Grant permissions
GRANT ALL ON feed_cost_log TO authenticated;
GRANT SELECT ON feed_cost_log TO anon;

-- Create function to update hog feed costs
CREATE OR REPLACE FUNCTION update_hog_feed_cost()
RETURNS TRIGGER AS $$
BEGIN
  -- Update the hog's total feed cost when a new feed cost log is added
  UPDATE hogs 
  SET total_feed_cost = (
    SELECT COALESCE(SUM(total_cost), 0) 
    FROM feed_cost_log 
    WHERE feed_cost_log.hog_id = NEW.hog_id
  )
  WHERE id = NEW.hog_id;
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger to automatically update hog feed costs
CREATE TRIGGER trigger_update_hog_feed_cost
AFTER INSERT ON feed_cost_log
FOR EACH ROW
EXECUTE FUNCTION update_hog_feed_cost();
